config/routes.rb
Rails.application.routes.draw do
  get 'admins/staff'

  get 'waiters/kitchen'

  get 'admins/categories'

  get 'admins/menu'

  get 'admins/home'

  get 'admins/stats'

  get 'admins/settings'

  get 'admins/tables'

  get 'admins/dishes'

  get 'admins/login'

  get 'tables/welcome'

  get 'tables/home'

  get 'waiters/login'

  get 'waiters/tables'

  get 'waiters/kitchen'

  root 'tables#welcome'

  post 'tables/redirect_to_table' => 'tables#redirect_to_table'

  delete 'sign_out' => 'sessions#destroy'
  delete 'admin_sign_out' => 'admin_sessions#destroy'

  get "waiters/tables_calling"
  get "waiters/clients_checking_out"
  get "waiters/table_served"

  resources :tables do
    post :toggle_request, on: :member
    post :finish_table, on: :member

  	resources :clients do
  		post :add_dish, on: :member
      post :remove_dish, on: :member
      
      post :toggle_check_out, on: :member
      post :cancel_check_out, on: :member
      post :toggle_done, on: :member

  	end
  end


  resources :client_sessions
  resources :admins do
    post :set_language, on: :member
  end
  resources :waiters
	resources :sessions
	resources :admin_sessions
  resources :menus do
    resources :categories do
    	resources :dishes
    end
  end
  EasyOrder::Application.routes.draw do
    get 'auth/:provider/callback', to: 'client_sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'client_sessions#destroy', as: 'signout'

    root to: "tables#welcome"
end

end

app/models/admin.rb
class Admin < ApplicationRecord
	has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :dishes
	belongs_to :menu

	def category_with_language
		"#{name} (#{self.menu.language})"
	end
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :dishes, :through => :order_tags
  has_many :order_tags

	belongs_to :table

	def bill_value
		total = 0
		dishes.each do |d|
			total += d.price
		end
		total
	end

	def first_name
    self.name.gsub(/\s+/m, ' ').strip.split(" ")[0]
  end

  def last_name
  	if self.name.gsub(/\s+/m, ' ').strip.split(" ").count > 1
  		self.name.gsub(/\s+/m, ' ').strip.split(" ")[-1]
  	end
  end

  def first_last_name
  	"#{first_name} #{last_name}"
  end

  def avatar_url
  	if self.uid.present?
  		"http://graph.facebook.com/#{self.uid}/picture?type=large"
  	else	
    	ActionController::Base.helpers.asset_path('default-avatar.png')
    end
  end

	def self.from_omniauth(auth)
    	where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |client|
      client.provider = auth.provider
      client.uid = auth.uid
      client.name = auth.info.name
      client.email = auth.info.email

      client.oauth_token = auth.credentials.token
      client.oauth_expires_at = Time.at(auth.credentials.expires_at)
      client.table = Table.new
      client.save!
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
	belongs_to :category

	has_many :clients, :through => :order_tags
	has_many :order_tags

	has_and_belongs_to_many :orders

	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>", xs: "50x50>" },
	 :default_url => ActionController::Base.helpers.asset_path('default-dish.png')
  	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :categories
end

app/models/order.rb
class Order < ApplicationRecord
	has_and_belongs_to_many :dishes
	belongs_to :waiter
	belongs_to :client

	def self.search(start_period, end_period)
	  Order.where("created_at >= ? AND created_at <= ?", start_period, end_period)
	end

	def bill_value
		total = 0
		dishes.each do |d|
			total += d.price
		end
		total
	end
end

app/models/order_tag.rb
class OrderTag < ApplicationRecord
	belongs_to :dish
	belongs_to :client
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :waiter
  has_many :clients
  validates :number, :uniqueness => true

  	def bill_value
		total = 0
		clients.each do |c|
			total += c.bill_value
		end
		total
	end

	def initialize(attributes={})
		super
		self.set_code
	end

	def set_code
		# Generate a random word with 8 characters
		while true do
	        o = [('1'..'9'),('a'..'z')].map { |i| i.to_a }.flatten
	        newCode = (0...8).map { o[rand(o.length)] }.join  
	        if not Table.find_by(code: newCode)
	          	break
	        end
	    end
	    self.code = newCode
	end
end

app/models/waiter.rb
class Waiter < ApplicationRecord
	has_many :tables
	has_many :orders
	has_secure_password
	validates :name, presence: true
	
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/time.rb
 module TimeHelper

 end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/admins/_new_admin.html.erb
<%= form_for @new do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name, class: "form-control" %><br>
	<%= f.label :password %><br>
	<%= f.password_field :password, required: true, class: "form-control" %><br>
	
	<%= f.submit "Add Admin", class: "form-control btn btn-primary" %>
<% end %>

app/views/admins/categories.html.erb
<div id="container" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<h2><%= t(:categories_you_have) %></h2>
<br>
<!-- <hr> -->
<% Menu.all.each do |m| %>
<br>
<h3 style="display:inline;"><%= "#{m.language} (#{m.categories.count})" %></h3>

<% if m.categories.count > 0 %>
<a id="<%= m.id %>" class="toggle-show pull-right" style="display:inline">Hide/Show</a>
<% end %>

<table id="menu-<%= m.id %>-content" class="menu-content table table-bordered ">
	<br><br>
	<% m.categories.each do |c| %>
		<tr>
			<td>
				<div class="text-left col-xl-6 col-md-6">
					<h3 class="no-margin"><%= c.name %></h3>
					<%= c.description %>
				</div>

				<div class="text-left col-xl-6 col-md-6">
					<%= link_to t(:delete), menu_category_path(m,c), :method => :delete, data: {confirm: 'Are you sure you want to delete this Waiter?'}, class: "btn btn-danger pull-right"%>

				<%= link_to t(:edit), edit_menu_category_path(m,c), class: "btn btn-primary pull-right"%>
				</div>
			</td>
		</tr>
	<% end %>
</table>
<hr>
<% end %>
<% if Menu.count != 0 %>
<button type="button" class="btn btn-primary " data-toggle="modal" data-target="#AddModal"><%= t(:add_category) %></button><br><br>

<div id="AddModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= t(:add_category) %></h4>
      </div>
      <div class="modal-body">
        <%= render "categories/new_category" %>
      </div>
    </div>
  </div>
</div>
<% else %>
	<h3><%= t(:add_menu_first) %></h3>
<% end %>

</div>

<script>

$( document ).ready(function(){
	$(".toggle-show").click(function(){
		var id = $(this).attr("id");
	    $("#menu-" + id + "-content").toggle();
	});
});
</script>

app/views/admins/dishes.html.erb
<div id="container" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<h2><%= t(:view_edit_menu) %></h2>
<% Menu.all.each do |m| %>

<% if m.categories.count == 0 then next end  %>

<h2 style="color:#2cb5e8"><%= "#{m.language} (#{m.locale})" %></h2>
<a id="<%= m.id %>" class="toggle-show pull-right" style="display:inline">Hide/Show</a>

<% m.categories.each do |c| %>
<h3 ><%= "#{c.name} (#{c.dishes.count})" %></h3>


<table class="table table-bordered menu-content table col-xs-12 " id="menu-<%= m.id %>-content" style="padding-left:30px;">

	<% c.dishes.each do |d| %>
		<tr>
			<td class="menuData">
				<div class="col-xl-1 col-md-1">
					<%= image_tag d.picture.url, class: "dishPicture img-circle" %>
				</div>
				<div class="text-left col-xl-7 col-md-7">
					<%= d.title %> ($ <%= d.price %>)<br>
					<%= d.description %><br>
				</div>
				<div class="text-left col-xl-4 col-md-4">
				<%= link_to t(:delete), menu_category_dish_path(m,d.category,d), :method => :delete, data: {confirm: 'Are you sure you want to delete this Dish?'}, class: "btn btn-danger pull-right"%>

				<%= link_to t(:edit), edit_menu_category_dish_path(m,d.category,d), class: "btn btn-primary pull-right"%>
				</div>
			</td>
		</tr>
	<% end %>
</table>
<% end %>
<% end %>
<% if Category.count != 0 %>
<br><br>

<button type="button" class="btn btn-primary " data-toggle="modal" data-target="#AddModal"><%= t(:add_dish) %></button><br><br>

	<div id="AddModal" class="modal fade" role="dialog">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title"><%= t(:add_dish) %></h4>
	      </div>
	      <div class="modal-body">
	        <%= render "dishes/new_dish" %>
	      </div>
	    </div>
	  </div>
	</div>
<% else %>
	<h3><%= t(:add_category_first) %></h3>
<% end %>
</div>

<script>

$( document ).ready(function(){
	$(".toggle-show").click(function(){
		var id = $(this).attr("id");
	    $("#menu-" + id + "-content").toggle();
	});
});
</script>

app/views/admins/home.html.erb
<div id="container" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-xs-12" style="text-align:center;">

<h2><%= t(:admin_home) %></h2>
<%= link_to admins_staff_path do %>
	<div class="homeCard col-xs-12">
		<%= image_tag "waiter", class: "cardImage"  %>
		<%= t(:staff) %>
	</div>
<% end %>

<%= link_to admins_menu_path  do %>
	<div class="homeCard col-xs-12">
		<%= image_tag "menu", class: "cardImage" %>
		<%= t(:menu) %>
	</div>
<% end %>

<%= link_to admins_categories_path do %>
	<div class="homeCard col-xs-12">
		<%= image_tag "categories_list", class: "cardImage" %>
		<%= t(:categories) %>
	</div>
<% end %>

<%= link_to admins_dishes_path  do %>
	<div class="homeCard col-xs-12">
		<%= image_tag "dishes", class: "cardImage" %>
		<%= t(:dishes) %>
	</div>
<% end %>

<%= link_to admins_stats_path do %>
	<div class="homeCard col-xs-4">
		<%= image_tag "stats", class: "cardImage" %>
		<%= t(:stats) %>
	</div>
<% end %>

<%= link_to admins_tables_path do%>
	<div class="homeCard col-xs-4">
		<%= image_tag "tables", class: "cardImage" %>
		<%= t(:tables) %>
	</div>
<% end %>

<%= link_to admins_settings_path do %>
	<div class="homeCard col-xs-4">
		<%= image_tag "settings", class: "cardImage" %>
		<%= t(:settings) %>
	</div>
<% end %>


</div>

app/views/admins/login.html.erb
<% Admin.count %>
<% Admin.all.each do |a| %>
	<% a.inspect %>
<% end %>

<div id="login">
<h2>Admin Login</h2>

<%= form_tag(admin_sessions_path, method: :create) do %>

  <h4>Name:</h4>
  <%= text_field :session, :name, placeholder: "Enter your name", required: true, class: "form-control" %>
  
  <h4>Password:</h4>
  <%= password_field :session, :password, placeholder: "Enter your password", required: true, class: "form-control"  %>
  <br>
  <%= submit_tag 'Login', class: "form-control btn-primary" %>
<% end %>


</div>

app/views/admins/menu.html.erb
<div id="container" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<h2><%= t(:menu_you_have) %></h2>
<!-- <hr> -->

<table class="table table-bordered">
	<% Menu.all.each do |m| %>	
		<tr>
			<td>
				<div class="text-left col-xl-6 col-md-6">
					<%= "#{t(:language)}: #{m.language}" %><br>
					<%= "#{t(:locale)}: #{m.locale}" %><br>
				</div>

				<div class="text-left col-xl-6 col-md-6">
					<%= link_to t(:delete), menu_path(m), :method => :delete, data: {confirm: 'Are you sure you want to delete this Menu?'}, class: "btn btn-danger pull-right"%>

				<%= link_to t(:edit), edit_menu_path(m), class: "btn btn-primary pull-right"%>
				</div>
			</td>
		</tr>
	<% end %>	
</table>
<!-- <hr> -->


<button type="button" class="btn btn-primary " data-toggle="modal" data-target="#AddModal"><%= t(:add_menu) %></button><br><br>

<div id="AddModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= t(:add_menu) %></h4>
      </div>
      <div class="modal-body">
        <%= render "menus/new_menu" %>
      </div>
    </div>
  </div>
</div>


</div>

app/views/admins/settings.html.erb
<div id="container" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-xs-12">
	<h1>Admins Settings</h1>
	<h3>Create Admin</h3>
	<%= render 'new_admin' %><br>

	<h3>Set Default Language</h3>
	
	<%= form_tag set_language_admin_path(current_admin) do %>

		
		<%= radio_button_tag(:language, "es_mx", true) %> Español<br>
		
		<%= radio_button_tag(:language, "pt_br", true) %> Português<br>
		
		<%= radio_button_tag(:language, "en", true) %> English<br>
		
		<%= submit_tag "Set Language", :class => 'btn btn-primary'%>

	<% end %>

</div>

app/views/admins/staff.html.erb
<div id="container" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

<h2><%= t(:this_is_your_staff) %></h2>



<h4><%= "#{@waiters.count} #{t(:registered_waiters)}" %></h4>

<table class="table table-bordered">
	<% @waiters.each do |w| %>
		<tr> 
			<td>
				<div class="text-left col-xl-6 col-md-6">
					<%= t(:name) %>: <%= w.name %><br>
					CPF: <%= w.cpf %><br>
					<%= t(:phone) %>: <%= w.phone %><br>
					<% if w.tables.count > 0 %>
					<%= t(:assigned_tables) %>: 
					<%= w.tables.collect {|t| t.number}.join ', '%>
					<% end %>
				</div>
				<div class="text-right col-xl-6 col-md-6">

				<%= link_to t(:delete), waiter_path(w), remote: true, :method => :delete, data: {confirm: 'Are you sure you want to delete this Waiter?'}, class: "btn btn-danger pull-right delete_waiter"%>


				<%= link_to t(:edit), edit_waiter_path(w), class: "btn btn-primary pull-right"%>
				</div>
			</td>
		</tr>
	<% end %>
</table>
<!-- </div> -->
<!-- <hr> -->
<br>
<button type="button" class="btn btn-primary " data-toggle="modal" data-target="#AddModal"><%= t(:add_waiter) %></button><br><br>

<div id="AddModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= t(:add_waiter) %></h4>
      </div>
      <div class="modal-body">
        <%= render "waiters/add_waiter" %>
      </div>
    </div>
  </div>
</div>
</div>

</script>

app/views/admins/stats.html.erb
<div id="stats-container" class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 tableHome">


<h2><%= t(:orders_between_dates) %></h2>


<%= form_tag admins_stats_path, :method => 'get', class: "form-inline inline-btn" do%>
    <label><%= t(:begin) %></label>
    <%= date_field :start_date, params[:start_date], :value => Time.now.strftime("%Y-%m-%d") %> 
    <label><%= t(:end) %></label>
    <%= date_field :end_date, params[:end_date], :value => Time.now.strftime("%Y-%m-%d") %>
    <%= submit_tag t(:search), class: "form-control btn btn-primary", 'data-disable-with' => "Please wait.." %>
<% end %>

<% text_field :start_date, params[:show_all], :value => "show" %> 

<%= form_tag admins_stats_path, :method => 'get', class: "form-inline inline-btn" do%>

    <%= submit_tag t(:show_all), class: "form-control btn btn-primary inline-btn", 'data-disable-with' => "Please wait.." %>
<% end %>
<hr>

<% total = 0 %>
<% @orders.each do |o|  %>
    <% total+=o.bill_value %>
<% end %>
<h3><%= "#{@orders.count} #{t(:orders_selected)}" %>  </h3>
<% if @start_date.present? and @end_date.present? and ((@end_date - @start_date).to_i / 1.day) > 1 %>
    <h5>Orders between <%= @start_date.strftime("%B, %-d") %> and <%= @end_date.strftime("%B, %-d") %></h5>
<% end %>
<h4>Total: <%= number_to_currency(total)%>
    <% if @start_date.present? and @end_date.present? and ((@end_date - @start_date).to_i / 1.day) > 1 %>
    - <%= number_to_currency(total / ((@end_date - @start_date).to_i / 1.day)) %>/day
    <% end %>
</h4>
<hr>


<%
data = {
  labels: I18n.t(:"date.day_names"),
  datasets: [
    {
        label: "Total sold By week day",
        backgroundColor: "rgba(124,223,134,1)",
        borderColor: "rgba(220,220,220,1)",
        data: value_at_weekday(@orders)
    }
  ]
}

dataHours = {
  labels: value_for_hour(@orders).keys,
  datasets: [
    {
        label: "Total sold by hour",
        backgroundColor: "rgba(124,223,134,1)",
        borderColor: "rgba(220,220,220,1)",
        data: value_for_hour(@orders).values
    }
  ]
}

dataWaiters = {
  labels: value_for_waiter(@orders).keys,
  datasets: [
    {
        label: "Total sold by Waiter",
        backgroundColor: "rgba(124,223,134,1)",
        borderColor: "rgba(220,220,220,1)",
        data: value_for_waiter(@orders).values
    }
  ]
}

options = {:height => "100", :scaleBeginAtZero => true}
optionsHours = {:height => "100", :scaleBeginAtZero => true}
optionsWaiters = {:height => "100", :scaleBeginAtZero => true}
%>

<h2><%= t(:sales_by_weekday) %></h2>
<%= line_chart data, options %>

<h2><%= t(:sales_by_hour) %></h2>
<%= line_chart dataHours, optionsHours %>

<h2><%= t(:sales_by_waiter) %></h2>
<%= line_chart dataWaiters, optionsWaiters %>
	<% @orders.each do |o|  %>
		<!-- .strftime("%T - %B, %-d - %Y ") -->
		<% o.inspect %><br>	
		Order created at: <%= I18n.l o.created_at.localtime, :format => "%T - %B, %-d - %Y " %><br>
		<% o.dishes.each do |d|%>
			<%= d.title %><br>
		<% end %>
        <% total += o.bill_value %>
		<br>
        
		Total: <%= number_to_currency(o.bill_value) %>
        <hr>
	<% end %><br>
    <hr>
    
</div>

app/views/admins/tables.html.erb
<div id="container" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

<h2><%= t(:view_edit_tables) %></h2>
<!-- <hr> -->
<table class="table table-bordered">
	<% @tables.each do |t| %>
		<% if t.number == 0 %>
			<% next %>
		<% end %>
		<tr>
			<td>
				<div class="text-left col-xl-6 col-md-6">
					<%= t(:table) %>: <%= t.number %><br>
					<%= t(:table_code) %>: <%= t.code %><br>
					Table's waiter: <%= t.waiter.name %>
				</div>
				<div class="text-left col-xl-6 col-md-6">
				<%= link_to t(:delete), table_path(t), :method => :delete, data: {confirm: 'Are you sure you want to delete this Table?'}, :remote => true, class: "btn btn-danger pull-right delete_table"%>

				<%= link_to t(:edit), edit_table_path(t), class: "btn btn-primary pull-right"%>
				</div>
			</td>
		</tr>
	<% end %>
</table>



<!-- <hr> -->

<button type="button" class="btn btn-primary " data-toggle="modal" data-target="#AddModal"><%= t(:add_table) %></button><br><br>


<div id="AddModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= t(:add_table) %></h4>
      </div>
      <div class="modal-body">
        <%= render "tables/new_table" %>
      </div>
    </div>
  </div>
</div>


</div>

app/views/layouts/_alerts.html.erb
<!-- Flash -->
<% if flash[:success] or flash[:error] %>
  <div id="message">
    <% if flash[:success] %>
      <div class="alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong><%= t(:success) %>!</strong> <%= flash[:success]%>
      </div>
    <%end%>
    <% if flash[:error] %>
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong><%= t(:error) %>!</strong> <%= flash[:error]%><br>
      </div>
    <%end%>
  </div>
<% end %>
<script>
  alertMessage();
</script>
<!-- Flash End -->
<br>

app/views/layouts/_toolbar.html.erb
<% if current_admin.present? %>
  <div id="toolbar">
  <%= "#{t(:logged_as)}: #{current_admin.name} (#{t(:admin)})" %> - 
  <%= link_to t(:admin_home), admins_home_path %> / 
  <%= link_to t(:tables), waiters_tables_path %> / <%= link_to t(:sign_out), admin_sign_out_path, method: :delete %><br>  
  </div>
<% end %>

<% if current_waiter.present? and not current_admin.present?%>
  <div id="toolbar">
    <%= "#{t(:logged_as)}: #{current_waiter.name}" %> - 
    <%= link_to t(:sign_out), sign_out_path, method: :delete %>
     / <%= link_to t(:tables), waiters_tables_path %>
     <br>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyOrder</title>
    <%= csrf_meta_tags %>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">

    <!-- Fonts -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= javascript_tag do %>
     $(function() {
       $("time.timeago").timeago();
     });
   <% end %>
    <%= render "layouts/toolbar" %>

    <div style="color:#fff;">    
      <% "Admin: #{current_admin.present?} 
     Client: #{current_client.present?}
     Waiter: #{current_waiter.present?} 
     Table: #{current_table.present?}" %>
   </div>

    <%= yield %>

    <%= render "layouts/alerts" %>


  </body>
</html>