config/routes.rb
Rails.application.routes.draw do
  get 'admins/staff'

  get 'waiters/kitchen'

  get 'admins/categories'

  get 'admins/menu'

  get 'admins/home'

  get 'admins/stats'

  get 'admins/settings'

  get 'admins/tables'

  get 'admins/dishes'

  get 'admins/login'

  get 'tables/welcome'

  get 'tables/home'

  get 'waiters/login'

  get 'waiters/tables'

  get 'waiters/kitchen'

  root 'tables#welcome'

  post 'tables/redirect_to_table' => 'tables#redirect_to_table'

  delete 'sign_out' => 'sessions#destroy'
  delete 'admin_sign_out' => 'admin_sessions#destroy'

  get "waiters/tables_calling"
  get "waiters/clients_checking_out"
  get "waiters/table_served"

  resources :tables do
    post :toggle_request, on: :member
    post :finish_table, on: :member

  	resources :clients do
  		post :add_dish, on: :member
      post :remove_dish, on: :member
      
      post :toggle_check_out, on: :member
      post :cancel_check_out, on: :member
      post :toggle_done, on: :member

  	end
  end


  resources :client_sessions
  resources :admins do
    post :set_language, on: :member
  end
  resources :waiters
	resources :sessions
	resources :admin_sessions
  resources :menus do
    resources :categories do
    	resources :dishes
    end
  end
  EasyOrder::Application.routes.draw do
    get 'auth/:provider/callback', to: 'client_sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'client_sessions#destroy', as: 'signout'

    root to: "tables#welcome"
end

end

app/models/admin.rb
class Admin < ApplicationRecord
	has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :dishes
	belongs_to :menu

	def category_with_language
		"#{name} (#{self.menu.language})"
	end
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :dishes, :through => :order_tags
  has_many :order_tags

	belongs_to :table

	def bill_value
		total = 0
		dishes.each do |d|
			total += d.price
		end
		total
	end

	def first_name
    self.name.gsub(/\s+/m, ' ').strip.split(" ")[0]
  end

  def last_name
  	if self.name.gsub(/\s+/m, ' ').strip.split(" ").count > 1
  		self.name.gsub(/\s+/m, ' ').strip.split(" ")[-1]
  	end
  end

  def first_last_name
  	"#{first_name} #{last_name}"
  end

  def avatar_url
  	if self.uid.present?
  		"http://graph.facebook.com/#{self.uid}/picture?type=large"
  	else	
    	ActionController::Base.helpers.asset_path('default-avatar.png')
    end
  end

	def self.from_omniauth(auth)
    	where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |client|
      client.provider = auth.provider
      client.uid = auth.uid
      client.name = auth.info.name
      client.email = auth.info.email

      client.oauth_token = auth.credentials.token
      client.oauth_expires_at = Time.at(auth.credentials.expires_at)
      client.table = Table.new
      client.save!
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
	belongs_to :category

	has_many :clients, :through => :order_tags
	has_many :order_tags

	has_and_belongs_to_many :orders

	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>", xs: "50x50>" },
	 :default_url => ActionController::Base.helpers.asset_path('default-dish.png')
  	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :categories
end

app/models/order.rb
class Order < ApplicationRecord
	has_and_belongs_to_many :dishes
	belongs_to :waiter
	belongs_to :client

	def self.search(start_period, end_period)
	  Order.where("created_at >= ? AND created_at <= ?", start_period, end_period)
	end

	def bill_value
		total = 0
		dishes.each do |d|
			total += d.price
		end
		total
	end
end

app/models/order_tag.rb
class OrderTag < ApplicationRecord
	belongs_to :dish
	belongs_to :client
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :waiter
  has_many :clients
  validates :number, :uniqueness => true

  	def bill_value
		total = 0
		clients.each do |c|
			total += c.bill_value
		end
		total
	end

	def initialize(attributes={})
		super
		self.set_code
	end

	def set_code
		# Generate a random word with 8 characters
		while true do
	        o = [('1'..'9'),('a'..'z')].map { |i| i.to_a }.flatten
	        newCode = (0...8).map { o[rand(o.length)] }.join  
	        if not Table.find_by(code: newCode)
	          	break
	        end
	    end
	    self.code = newCode
	end
end

app/models/waiter.rb
class Waiter < ApplicationRecord
	has_many :tables
	has_many :orders
	has_secure_password
	validates :name, presence: true
	
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
	def create
    	@menu = Menu.new(menu_params)
      @menu.locale = @menu.locale.downcase
    	if @menu.save
      	flash[:success] = t(:menu_added)
      	redirect_to admins_menu_path
    	end
  	end

    def edit
      @menu = Menu.find(params[:id])
    end

    def update
      @menu = Menu.find(params[:id])
      if @menu.update_attributes(menu_params)
        @menu.locale = @menu.locale.downcase
        @menu.save
        flash[:success] = t(:menu_edited)
        redirect_to admins_menu_path
      else
        redirect_to :back
      end
    end

    def destroy
      @menu = Menu.find(params[:id])
      flash[:success] = t(:menu_destroyed)
      @menu.destroy
      redirect_to :back
    end

	def menu_params
    	params.require(:menu).permit(:language,:locale)
  	end
end

app/controllers/waiters_controller.rb
class WaitersController < ApplicationController
	
  	def create
    	@waiter = Waiter.new(waiter_params)
    
    	if @waiter.save
      	flash[:success] = t(:waiter_added)
      	redirect_to admins_staff_path
    	end
  	end

    def kitchen
      # @tags = OrderTag.where("created_at > ?", Time.at(params["after"].to_i + 1)).order("created_at ASC")
      @tags = OrderTag.order("created_at ASC")
    end

    def table_served
      @tag = OrderTag.find(params[:tag])
      @tag.served = !@tag.served
      @tag.save
      redirect_to :back
    end

    def edit
      @waiter = Waiter.find(params[:id])
    end

    def update
      @waiter = Waiter.find(params[:id])
      if @waiter.update_attributes(waiter_params)
        @waiter.save
        flash[:success] = t(:waiter_edited)
        redirect_to waiters_manage_employees_path
      else
        render :edit
      end
    end

  	def login
  		reset_session
  	end

  	def tables
      non_waiter_redirect
  		@tables = Table.order("number asc")
      session[:client_id] = nil
      session[:table_id] = nil
  	end

    def tables_calling
      calling = []
      @tables = Table.all
      @tables.where(requested: true).each do |table|
        calling << table.id
      end
      render json: calling
    end

    def clients_checking_out
      checking_out = []
      Table.all.each do |t|
        t.clients.each do |c|
          if c.payment_method.present? and not c.done
            checking_out << t.id
          end
        end
      end
      render json: checking_out
    end
    
    def destroy
      @waiter = Waiter.find(params[:id])
      @waiter.destroy
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { head :no_content }
        format.js   { render :layout => false }
     end
      # flash[:success] = t(:waiter_destroyed)
      # redirect_to :back
    end

    def non_waiter_redirect
      if not current_waiter.present? and not current_admin.present?
        redirect_to root_path
      end
    end

	  def waiter_params
    	params.require(:waiter).permit(:name, :cpf, :phone, :password)
  	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/time.rb
 module TimeHelper

 end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/waiters/_add_waiter.html.erb
<%= form_for @new do |f| %>
<%= f.label t(:name) %><br>
<%= f.text_field :name, required: true, class: "form-control"%>
<br>

<%= f.label :cpf %><br>
<%= f.number_field :cpf, class: "form-control"%>

<br>

<%= f.label t(:phone) %><br>
<%= f.text_field :phone, class: "form-control"%>

<br>
<%= f.label :password, t(:enter_password) %>
  <br>
  <%= f.password_field :password, required: true, class: "form-control"%>
<br>

<button type="button" class="btn btn-danger" data-dismiss="modal"><%= t(:close) %></button>
<%= f.submit t(:add_waiter), class: "btn btn-primary" %>

<% end %>

app/views/waiters/_tag.html.erb
<div class="kitchen-card" style="text-align:left">
	<h3><%= t.dish.title %> - <%= t.dish.category.name %></h3>
	<h5>Table: <%= t.client.table.number %></h5>

	Ordered at 
	<%= I18n.l t.created_at.localtime, :format => "%T" %>
	<span class="timeAgo" data-time="<%= t
	.created_at.localtime %>"></span>


	 <%= link_to_if(!t.served,"Set as served", waiters_table_served_path(id: Waiter.first, tag: t) ,class: "btn btn-success pull-right"){} %>

	 <%= link_to_if(t.served,"Set as not served", waiters_table_served_path(id: Waiter.first, tag: t) ,class: "btn btn-success pull-right"){} %>
</div>

app/views/waiters/destroy.js.erb
$('.delete_waiter').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/waiters/edit.html.erb
<div id="container" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<br>
<h2><%= t(:edit_waiter) %></h2>

<%= form_for @waiter do |f| %>
<%= f.label t(:name) %><br>
<%= f.text_field :name, required: true, class: "form-control"%>
<br>

<%= f.label :cpf %><br>
<%= f.number_field :cpf, class: "form-control"%>

<br>

<%= f.label t(:phone) %><br>
<%= f.text_field :phone, class: "form-control"%>

<br>
<%= f.label :password, t(:enter_password) %>
  <br>
  <%= f.password_field :password, required: true, class: "form-control"%>
<br>
<%= f.submit t(:save_edit), class: "btn btn-primary" %>
<br><br>
<% end %>
</div>

app/views/waiters/kitchen.html.erb
<div style="text-align:center;" id="kitchen-orders">
	<% @tags.each do |t| %>
		<%= render 'tag', :t => t %>
	<% end %>
</div>


<script>	
	timeAgo();
	setInterval( timeAgo , 10000);

	function timeAgo()
	{
		$(".timeAgo").each(function(index){
			console.log($(this).attr("data-time"));
			var dateVar = $(this).attr("data-time");
			var d = new Date(dateVar);
			var dif = Math.round(((new Date()) - d)/60000);
			$(this).empty();
			$(this).append("(" + dif + " minutes ago)");
		});
	}

</script>

app/views/waiters/login.html.erb
<div id="login">
<h2>Staff Login</h2>

<%= form_tag(sessions_path, method: :create) do %>

  <h4>Name:</h4>
  <%= text_field :session, :name, placeholder: "Enter your name", required: true, class: "form-control"%>
  
  <h4>Password:</h4>
  <%= password_field :session, :password, placeholder: "Enter your password", required: true, class: "form-control"  %>
  <br>
  <%= submit_tag 'Login', class: "form-control btn-primary" %>
<% end %>

</div>

app/views/waiters/tables.html.erb
<% @tables.each do |t| %>
	<% if (true) and t.number %>
		<div class="tableCard" id="table-<%=t.id%>">
			<div id="table<%=t.number%>-header">
			<h5>
			- (<%=t.clients.count%>)
			<%= link_to "#{t(:table)} #{t.number}", tables_home_path(id: t) %> 
			(<%= t.code %>) -
			</h5>
			</div>
			<div id="table<%=t.number%>-content" class="tables-content">
				<% t.clients.each do |c| %>
					<%= link_to c.first_last_name, table_client_path(t,c) %> 

					<%= link_to_if(!c.done, t(:done), toggle_done_table_client_path(t,c), method: :toggle_done, data: 
					{ confirm: t(:is_this_client_done) }, :class => 'pull-right'){} %>

        			<%= link_to_if(c.done, t(:undone),toggle_done_table_client_path(t,c), method: :toggle_done, data: 
        			{ confirm: 'Is this client not done?' }, :class => 'pull-right'){}%>

					<br>
					($<%= number_with_precision(c.bill_value, :precision => 2) %>)
					<% if c.payment_method.present? %>
						<span class="pull-right"><%= "#{t(:paying_with)} #{c.payment_method}" %></span>
					<% end %>
					<br>
					<% link_to "Delete client", table_client_path(t,c), method: :delete %>

					<div class="tableOrders">
						<% c.order_tags.each do |o| %>
							<%= o.dish.title %>
							<% o.dish.price %>
							<%= link_to t(:delete), remove_dish_table_client_path(t,tag: o, id:o.client.id), method: :post, data: {confirm: t(:delete_dish_from_client)}, class: "pull-right"%> 
							<br>
						<% end %>
					</div>
					<hr>
				<% end %>
				
				<% if t.clients.count != 0 %>
					<br>
					Total: <%= number_with_precision(t.bill_value, :precision => 2) %>
					<br>
					<%= link_to_if(t.requested, t(:toggle_request), toggle_request_table_path(t,table_id: t, user: 1), method: :post){}%>

				<%else%>
					<%= t(:empty_table) %>
				<%end%>
			</div> <!-- TableX-content -->

			<% if t.clients.count != 0 %>
				<a class="toggle-show" id="<%= t.number %>">
					- <%= t(:toggle_show) %> -
				</a>
			<% end %>

			<%= link_to_if((t.clients.count != 0), t(:finish_table), finish_table_table_path(t.waiter,table_id: t.id), method: :post, data: { confirm: t(:finish_table_prompt) }){}%>

		</div> <!-- Tables --> 
	<%end%>
<%end%> <!-- t defined end -->
<br>
<% OrderTag.all.each do |o| %>
	<%= o.inspect %><br>
<% end %>


<script type="text/javascript">
setInterval( updateTables , 5000);

function updateTables() {
  $.getJSON('/waiters/tables_calling', function (data)
  {
    $('.tableCard').removeClass('calling');
    for (var i = 0; i < data.length; i++)
    {
    	console.log(data[i]);
    	$('#table-' + data[i]).addClass('calling')
    }
  });
  $.getJSON('/waiters/clients_checking_out', function (data)
  {
    $('.tableCard').removeClass('checking_out');
    for (var i = 0; i < data.length; i++)
    {
    	console.log(data[i]);
    	$('#table-' + data[i]).addClass('checking_out')
    }
  });
}

$( document ).ready(function(){
	$(".toggle-show").click(function(){
		var tableID = $(this).attr("id");
	    $("#table" + tableID + "-content").toggle("fast");
	});
});
</script>