config/routes.rb
Rails.application.routes.draw do
  get 'admins/staff'

  get 'waiters/kitchen'

  get 'admins/categories'

  get 'admins/menu'

  get 'admins/home'

  get 'admins/stats'

  get 'admins/settings'

  get 'admins/tables'

  get 'admins/dishes'

  get 'admins/login'

  get 'tables/welcome'

  get 'tables/home'

  get 'waiters/login'

  get 'waiters/tables'

  get 'waiters/kitchen'

  root 'tables#welcome'

  post 'tables/redirect_to_table' => 'tables#redirect_to_table'

  delete 'sign_out' => 'sessions#destroy'
  delete 'admin_sign_out' => 'admin_sessions#destroy'

  get "waiters/tables_calling"
  get "waiters/clients_checking_out"
  get "waiters/table_served"

  resources :tables do
    post :toggle_request, on: :member
    post :finish_table, on: :member

  	resources :clients do
  		post :add_dish, on: :member
      post :remove_dish, on: :member
      
      post :toggle_check_out, on: :member
      post :cancel_check_out, on: :member
      post :toggle_done, on: :member

  	end
  end


  resources :client_sessions
  resources :admins do
    post :set_language, on: :member
  end
  resources :waiters
	resources :sessions
	resources :admin_sessions
  resources :menus do
    resources :categories do
    	resources :dishes
    end
  end
  EasyOrder::Application.routes.draw do
    get 'auth/:provider/callback', to: 'client_sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'client_sessions#destroy', as: 'signout'

    root to: "tables#welcome"
end

end

app/models/admin.rb
class Admin < ApplicationRecord
	has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :dishes
	belongs_to :menu

	def category_with_language
		"#{name} (#{self.menu.language})"
	end
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :dishes, :through => :order_tags
  has_many :order_tags

	belongs_to :table

	def bill_value
		total = 0
		dishes.each do |d|
			total += d.price
		end
		total
	end

	def first_name
    self.name.gsub(/\s+/m, ' ').strip.split(" ")[0]
  end

  def last_name
  	if self.name.gsub(/\s+/m, ' ').strip.split(" ").count > 1
  		self.name.gsub(/\s+/m, ' ').strip.split(" ")[-1]
  	end
  end

  def first_last_name
  	"#{first_name} #{last_name}"
  end

  def avatar_url
  	if self.uid.present?
  		"http://graph.facebook.com/#{self.uid}/picture?type=large"
  	else	
    	ActionController::Base.helpers.asset_path('default-avatar.png')
    end
  end

	def self.from_omniauth(auth)
    	where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |client|
      client.provider = auth.provider
      client.uid = auth.uid
      client.name = auth.info.name
      client.email = auth.info.email

      client.oauth_token = auth.credentials.token
      client.oauth_expires_at = Time.at(auth.credentials.expires_at)
      client.table = Table.new
      client.save!
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
	belongs_to :category

	has_many :clients, :through => :order_tags
	has_many :order_tags

	has_and_belongs_to_many :orders

	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>", xs: "50x50>" },
	 :default_url => ActionController::Base.helpers.asset_path('default-dish.png')
  	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :categories
end

app/models/order.rb
class Order < ApplicationRecord
	has_and_belongs_to_many :dishes
	belongs_to :waiter
	belongs_to :client

	def self.search(start_period, end_period)
	  Order.where("created_at >= ? AND created_at <= ?", start_period, end_period)
	end

	def bill_value
		total = 0
		dishes.each do |d|
			total += d.price
		end
		total
	end
end

app/models/order_tag.rb
class OrderTag < ApplicationRecord
	belongs_to :dish
	belongs_to :client
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :waiter
  has_many :clients
  validates :number, :uniqueness => true

  	def bill_value
		total = 0
		clients.each do |c|
			total += c.bill_value
		end
		total
	end

	def initialize(attributes={})
		super
		self.set_code
	end

	def set_code
		# Generate a random word with 8 characters
		while true do
	        o = [('1'..'9'),('a'..'z')].map { |i| i.to_a }.flatten
	        newCode = (0...8).map { o[rand(o.length)] }.join  
	        if not Table.find_by(code: newCode)
	          	break
	        end
	    end
	    self.code = newCode
	end
end

app/models/waiter.rb
class Waiter < ApplicationRecord
	has_many :tables
	has_many :orders
	has_secure_password
	validates :name, presence: true
	
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  def welcome
    if current_client.present? and current_table.present?
      redirect_to tables_home_path
    end
  end

  def redirect_to_table
		@table = Table.find_by(:code => params[:code])

		if @table.present?
      if current_client.present?
        @client = current_client
        @client.table = @table
        @client.done = false
        @client.payment_method = nil
        @client.save
      end
			session[:table_id] = @table.id
      flash[:success] = "#{t(:welcome_to_table)} #{@table.number}"
			redirect_to tables_home_path
		else
			flash[:error] = t(:incorrect_code)
			redirect_to root_path
		end
	end

  def home
  	@new = Client.new
    if not current_table.present?
      session[:table_id] = params[:id]
    end

    if current_client.present?
      if not current_client.table.present?
        reset_session
        redirect_to root_path
      end
    end
  end

  def edit
    @table = Table.find(params[:id])
  end

  def create
  	@table = Table.new(table_params)
    begin
    	if @table.save!
        flash[:success] = t(:table_created)
    		redirect_to admins_tables_path
    	end
      rescue ActiveRecord::RecordInvalid => e
        if e.message == "Validation failed: Number has already been taken"
          flash[:error] = t(:unique_table)
          redirect_to admins_tables_path
        end
    end
  end

  def update
    @table = Table.find(params[:id])
    if @table.update_attributes(table_params)
      @table.save
      flash[:success] = t(:table_edited)
      redirect_to admins_tables_path
    else
      redirect_to :back
    end
  end

  def finish_table
    @table = Table.find(params[:table_id])
    done = true
    @order = Order.new

    @table.clients.each do |c|
      if !c.done
        done = false
        flash[:error] = t(:not_done_finish)
        redirect_to :back
      end
    end

    if done
      @table.clients.each do |c|
        c.dishes.each do |d|
          @order.dishes << d
        end
        c.dishes = []
        flash[:success] = t(:table_finished)
      end

      if @order.bill_value > 0
        @order.waiter = @table.waiter
        @order.client = @table.clients.first
        @order.save!
      end

      @table.clients = []
      @table.requested = false

      
      @table.set_code

      @table.save
      redirect_to waiters_tables_path
    end
  end 

  def toggle_request
    @table = Table.find(params[:table_id])
    @table.requested = !@table.requested
    @table.save
    redirect_to :back
  end

  def destroy
    @table = Table.find(params[:id])
    @table.destroy
    # flash[:success] = t(:table_destroyed)
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
      format.js   { render :layout => false }
   end
  end

  def table_params
  	params.require(:table).permit(:code, :number, :waiter_id, :requested)
  end 

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/time.rb
 module TimeHelper

 end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/tables/_new_table.html.erb
<%= form_for @new do |f| %>

<%= f.label t(:table_number) %><br>
<%= f.number_field :number, :step => 1, min: 1, required: true, class: "form-control"%>
<br>
<%= f.label t(:code) %><br>
<%= f.text_field :code, required: true, value: @new.set_code, class: "form-control"%>
<br>
<%= f.label :waiter, t(:waiter_assigned) %>
  <br>
  <%= f.collection_select :waiter_id, Waiter.all, :id, :name, include_blank: false, class: "form-control"%>
  <br><br>

  <button type="button" class="btn btn-danger" data-dismiss="modal"><%= t(:close) %></button>

<%= f.submit t(:add_table), class: "btn btn-primary" %>

<% end %>

app/views/tables/destroy.js.erb
$('.delete_table').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/tables/edit.html.erb
<div id="container" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	<h2><%= t(:edit_table) %></h2>
<%= form_for @table do |f| %>

<%= f.label t(:table_number) %><br>
<%= f.number_field :number, :step => 1, min: 1, required: true, class: "form-control"%>
<br>
<%= f.label t(:code) %><br>
<%= f.text_field :code, required: true, class: "form-control"%>
<br>
<%= f.label :waiter, t(:waiter_assigned) %>
  <br>
  <%= f.collection_select :waiter_id, Waiter.all, :id, :name, include_blank: false, class: "form-control"%>
  <br><br>


<%= f.submit t(:save_edit), class: "btn btn-primary" %>
<br><br>
<% end %>
</div>

app/views/tables/home.html.erb
<!-- Waiter log client in END -->
<% if not current_waiter.present? and not current_admin.present? %>
<div onclick="openNav()" class="mobile-profile mobile-profile-toolbar">
	<div class="pull-left hamb-menu">
		<h2 style="display:inline;">
			<i class="fa fa-bars" aria-hidden="true"></i>
		</h2>
	</div>
	<img src="<%= current_client.avatar_url %>" class="img-circle toolbar-user-image">
	<h3 style="display:inline;">
		<%= current_client.first_last_name %> 
	</h3>
</div>
<% end %>
<!-- Client toolbar -->

<div id="container-table" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1  tableHome">

<!-- Waiter log client in -->

<% if not current_client.present? %>
	<div class="mobile-profile">
		<%= form_for([current_table,@new]) do |f| %>
			<%= f.label t(:name) %><br>
			<%= f.text_field :name, class: "form-control", required: true %><br>
			<%= f.submit t(:login), class: "btn btn-primary" %>
		<% end %>
	</div>
<% end %>

<!-- Client toolbar END -->

<!-- PROFILE FOR MOBILE END -->
<div id="profileSidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <% if current_client.present? %><br>
	<img src="<%= current_client.avatar_url %>" class="img-circle avatar"><br>
	<h3> <%= current_client.first_last_name %> </h3>
	<!-- Request Waiter -->
	<% if current_client.table.requested %>
		<h5><%= t(:waiter_called) %></h5>
	<%else%>
	
	<h5><%=link_to t(:call_waiter), toggle_request_table_path(current_client.table,table_id: current_client.table), user: 2, method: :post, class: "sidenav-link" %></h5>
	<%end%>

	<!-- Request Waiter End -->
	
	<!-- Orders -->
	<% if current_client.dishes.count > 0 %>
		<h4><%= t(:you_have_ordered) %></h4>
		<div id="orders">
			<% current_client.dishes.each do |d| %>
				<h5><%= d.title %></h5>
			<% end %>
		</div>
		<h4><%= t(:total) %>: $<%= number_with_precision(current_client.bill_value, :precision => 2) %></h4>
	<% else %>
		<h4><%= t(:no_orders) %></h4>
		<h4><%= t(:hungry) %></h4>
	<% end %>
	<!-- Orders End -->

	<!-- Check out -->
	
	<% if not current_client.payment_method.present? and current_client.dishes.count > 0%>
	<br>
		<a class="toggle-payment btn btl-xs btn-success" style="color: #fff;">
					<%= t(:select_check_out) %>
				</a>
		<div class="check-out">
			<%= form_tag toggle_check_out_table_client_path(current_table,current_client) do %>
					<%= t(:credit) %> <%= radio_button_tag(:payment_method, t(:credit), true,:item_wrapper_class => 'inline') %>
					<%= t(:cash) %> <%= radio_button_tag(:payment_method, t(:cash),:item_wrapper_class => 'inline md-radio-button') %><br>
					<%= submit_tag t(:check_out), :class => 'btn btn-primary checkOutBtn'%>

			<% end %>
		</div>
	<% elsif current_client.payment_method.present? %>
		<div style="color:#24BD4B; margin-bottom:5px; font-size:16px;">
			<%= "#{t(:paying_with)} #{current_client.payment_method}" %>
		</div>

		<%= link_to t(:cancel_check_out),cancel_check_out_table_client_path(current_table,current_client), method: :cancel_check_out, class: "btn-sm btn-danger btn" %>
		<br><br>
	<% end %>

	<!-- Check out END -->

	<hr>

	<% end %>
	<!-- Who's on the table -->
	<% if current_table.clients.count > 1 %>
		
		<div class="col-xs-12 col-md-12 people-on-table">
			<%= t(:who_is_on) %><br>
			<% current_table.clients.each do |c| %>
				<div class="col-xs-4">
					<img src="<%= c.avatar_url %>" class="img-circle thumb"><br>
					<%= c.first_name %>
				</div>
			<% end %>
		</div>
	<% end %>
	<!-- Who's on the table END-->
	<br>

	
	<%= "#{t(:table_code)}: #{current_table.code}" %>

	<div id="languages-menu">
		<%= t(:languages) %>:<br>
			<% Menu.all.each do |m| %>
				<%= link_to m.language, :locale =>m.locale, class: "sidenav-link"%><br>
			<% end %>
	</div>
</div>
<!-- PROFILE FOR MOBILE END -->

<!-- PROFILE FOR DESKTOP -->
<div class="col-lg-4 col-md-4" id="profile">

	<% if not current_client.present? %>
		<%= form_for([current_table,@new]) do |f| %>
			<%= f.label t(:name) %><br>
			<%= f.text_field :name, class: "form-control", required: true %><br>
			<%= f.submit t(:login), class: "btn btn-primary" %>
		<% end %>
	<% end %>

	<% if current_client.present? %><br>
	<img src="<%= current_client.avatar_url %>" class="img-circle avatar"><br>
	<h3> <%= current_client.first_last_name %> </h3>
	<!-- Request Waiter -->
	<% if current_client.table.requested %>
		<h5><%= t(:waiter_called) %></h5>
	<%else%>
	
	<h5><%=link_to t(:call_waiter), toggle_request_table_path(current_client.table,table_id: current_client.table), user: 2, method: :post %></h5>
	<%end%>

	<!-- Request Waiter End -->
	
	<!-- Orders -->
	<% if current_client.dishes.count > 0 %>
		<h4><%= t(:you_have_ordered) %></h4>
		<div id="orders">
			<% current_client.dishes.each do |d| %>
				<h5><%= d.title %></h5>
			<% end %>
		</div>
		<h4><%= t(:total) %>: $<%= number_with_precision(current_client.bill_value, :precision => 2) %></h4>
	<% else %>
		<h4><%= t(:no_orders) %></h4>
		<h4><%= t(:hungry) %></h4>
	<% end %>
	<!-- Orders End -->



	<!-- Check out -->
	
	<% if not current_client.payment_method.present? and current_client.dishes.count > 0%>
	<br>
		<a class="toggle-payment btn btl-xs btn-success">
					<%= t(:select_check_out) %>
				</a>
		<div class="check-out">
			<%= form_tag toggle_check_out_table_client_path(current_table,current_client) do %>
					<%= t(:credit) %> <%= radio_button_tag(:payment_method, t(:credit), true,:item_wrapper_class => 'inline') %>
					<%= t(:cash) %> <%= radio_button_tag(:payment_method, t(:cash),:item_wrapper_class => 'inline') %><br>
					<%= submit_tag t(:check_out), :class => 'btn btn-primary checkOutBtn'%>
			<% end %>
		</div>
	<% elsif current_client.payment_method.present? %>
		<div style="color:#24BD4B; margin-bottom:5px; font-size:16px;">
			<%= "#{t(:paying_with)} #{current_client.payment_method}" %>
		</div>

		<%= link_to t(:cancel_check_out),cancel_check_out_table_client_path(current_table,current_client), method: :cancel_check_out, class: "btn-sm btn-danger" %>
		<br><br>
	<% end %>

	<!-- Check out END -->

	<% end %>
	<!-- Who's on the table -->
	<% if current_table.clients.count > 1 %>
		<hr>
		<div class="col-xs-12 col-md-12 people-on-table">
			<%= t(:who_is_on) %><br>
			<% current_table.clients.each do |c| %>
				<div class="col-xs-4">
					<img src="<%= c.avatar_url %>" class="img-circle thumb"><br>
					<%= c.first_name %>
				</div>
			<% end %>
		</div>
	<% end %>
	<!-- Who's on the table END-->
	<br>
	<hr>
</div>
<!-- PROFILE FOR DESKTOP END -->

<!-- Menu -->
<div class="col-lg-8 col-md-8" id="menu"  onclick="closeNav()">
	
	<% m = Menu.find_by(locale: current_locale) %>
	<div id="category">
		<% m.categories.each do |c| %>
			<h2 class="category-title"><%= c.name %></h2>
			<!-- <h4><% c.description %></h4> -->
			<table class="table table-borderless category-table">


			<% c.dishes.each do |d| %>

			<!-- Dish -->
			<tr id="dish-<%= d.id %>-details" class="dish-details-data">
				<td class="menuData">
					<div class="col-xl-12 col-md-12 dish-frame">
						<%= image_tag d.picture.url, class: "dish-picture-home " %>
					</div>
					<div class="text-left col-xl-12 col-md-12">
						<h3 class="line-clamp"><%= d.title %></h3>

						<div class="more">
						<%= d.description %>
						</div>

					</div>
					<div class="text-left col-xl-12 col-md-12">
					<%= link_to_if((current_client.present? and not current_client.done), "#{t(:order)} $#{number_with_precision(d.price, :precision => 2)}",add_dish_table_client_path(current_table, current_client, dish_id: d.id, id: d.id), method: :post, data: 
	    			{ confirm: t(:confirm_order) }, :class => 'btn btn-success pull-right order-btn '){}%>
	    			<!-- <button id="<%= d.id %>" class="toggle-details pull-right btn btn-info ">Less</button>	 -->
					</div>
				</td>
			</tr>
			<!-- Dish END -->
			<% end %>
			</table>
		<% end %>
	</div>
</div><br>
<br>
</div>

<script>

$( document ).ready(function(){
	$(".check-out").hide();
	$(".toggle-payment").click(function(){
	    $(".check-out").toggle("fast");
	});
});

/* Set the width of the side navigation to 250px */

function openNav() {

	if ($(window).width() <= 768 && $(window).width() > 580 )
	{
		document.getElementById("profileSidenav").style.width = "450px";
		
	}
 	if ($(window).width() < 580  && $(window).width() > 300 )
 	{ 
 		document.getElementById("profileSidenav").style.width = "300px";
 	}
 	if ($(window).width() < 300 )
	{ 
 		document.getElementById("profileSidenav").style.width = "100%";
 	}
}

/* Set the width of the side navigation to 0 */
function closeNav() {
    document.getElementById("profileSidenav").style.width = "0";
}

</script>

<style>
table {
    border-collapse: separate;
    border-spacing: 0 1em;
}
</style>

app/views/tables/welcome.html.erb
<div id="welcome">
	<img src="http://homologacao.digitalmenu.com.br/files/07192015112137logo.png" id="restaurant-logo">
	<% if current_client.present? %>
	<%=form_tag(tables_redirect_to_table_path) do %>
		Enter Table Code:
	    <%= text_field_tag :code,"", maxlength: 15, class: "form-control", placeholder: "Ask the waiter for your code" %><br>
	    <%= submit_tag 'Go to table', class: "form-control btn-primary" %>
	<%end%>
	<% else %>
	
	<h5>Sign in with Facebook first</h5>

	<%= link_to "/auth/facebook", id: "sign_in", class: "btn btn-block btn-social btn-facebook" do %>
		<span class="fa fa-facebook"></span> Login with Facebook
		<% end %>



	<% end %>


	<br>

</div>